[runtime]
host = "0.0.0.0"
port = 23457

[auth]
resona_secret = ""

[worker]
pool_size = 2
default_timeout_ms = 8000
wl_timeout_ms = 12000

[masterdata.jp]
location = ""
fallback = [
  "",
  "",
]
musicmeta = ""
musicmeta_fallback = [""]
masterdata_override = true

[masterdata.cn]
location = "masterdata/cn"
fallback = [
  "",
  "",
]
musicmeta = ""
musicmeta_fallback = [""]

[masterdata.tw]
location = ""
fallback = [
  "",
  "",
]
musicmeta = ""
musicmeta_fallback = [""]
